### ISSUE TITLE
Suggestions on Readme.md readability.

### ISSUE THREAD

**Issue by ilyas-accenture** [vooolll/facebook4s#10]
### Readability
`Client id` and `application secret` should be marked as code. [Configuration](samplelink) must be a link to the section of the document.
![screen shot 2017-10-11 at 18 00 39](https://user-images.githubusercontent.com/31214616/31448881-29c02f14-aeae-11e7-9666-271e24ddf9f2.png)
### Grammar
This should be "to your advantage".
![screen shot 2017-10-11 at 18 02 00](https://user-images.githubusercontent.com/31214616/31448985-6a29e216-aeae-11e7-93b8-3c93edd78d11.png)
This should be "long life token"
![screen shot 2017-10-11 at 18 03 53](https://user-images.githubusercontent.com/31214616/31449067-a2de5fe2-aeae-11e7-9820-3071f05dc553.png)

**Comment by vooolll** [comment]
@ilyas-accenture Tt is known as long-lived access token from documentation, so I keep naming it like that. https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension/.  Fixed - https://github.com/vooolll/facebook4s/commit/a688116a41de9e3de20a85ff1f93a9e83f376cec
